version: '3.8'

services:
  ir-auto:
    build:
      context: '.'
      dockerfile: dev.Dockerfile
    ports:
      - 5000:8083
    volumes:
      - ./src:/app/src
      - /node_modules
    env_file: ./.env
    environment:
      - REDIS_URL=redis://redis:6379/0?password=XQ7pRIe6Ae
    depends_on:
      - redis

  redis:
    image: redis:5.0.10-alpine
    command: redis-server --requirepass XQ7pRIe6Ae
    ports:
      - 6379:6379
